SportsStore/Controllers/API/ShoesController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SportsStore.Controllers.API
{
    public class ShoesController : ApiController
    {
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();

        // GET: api/Shoes
        public IHttpActionResult Get()
        {
            try { 
            List<Shoe>ListShoes= dbContext.Shoes.ToList();
            return Ok(new {ListShoes});
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: api/Shoes/5
        public IHttpActionResult Get(int id)
        {
            try { 
            Shoe shoes = dbContext.Shoes.First(item => item.Id == id);
            return Ok(new { shoes });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // POST: api/Shoes
        public IHttpActionResult Post([FromBody]Shoe shoes)
        {
            try { 
            dbContext.Shoes.InsertOnSubmit(shoes);
            dbContext.SubmitChanges();
            List<Shoe> ListShoes = dbContext.Shoes.ToList();
            return Ok(new { ListShoes });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // PUT: api/Shoes/5
        public IHttpActionResult Put(int id, [FromBody]Shoe shoes)
        {
            try { 
            Shoe shoesToChange = dbContext.Shoes.First(item => item.Id == id);
            shoesToChange.Img = shoes.Img;
            shoesToChange.IsSale=shoes.IsSale;
            shoesToChange.Amount = shoes.Amount;
            shoesToChange.Company=shoes.Company;
            shoesToChange.Price = shoes.Price;
            shoesToChange.ShoeType = shoes.ShoeType;
            shoesToChange.Model = shoes.Model;
            dbContext.SubmitChanges();
            return Ok("you upDate");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // DELETE: api/Shoes/5
        public IHttpActionResult Delete(int id)
        {
            try { 
            Shoe shoesToDelete = dbContext.Shoes.First(item => item.Id == id);
            dbContext.Shoes.DeleteOnSubmit(shoesToDelete);
            dbContext.SubmitChanges();
            return Ok("you delete");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

SportsStore/Controllers/ShoesController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ShoesController : Controller
    {
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();
        // GET: Shoes

        public ActionResult CardShoes()
        {
            List<Shoe> listShoes = dbContext.Shoes.ToList();
            return View(listShoes);
        }
        public ActionResult TableShoes()
        {
            List<Shoe> listShoes = dbContext.Shoes.ToList();
            return View(listShoes);
        }
        public ActionResult SaleShoes()
        {
            List<Shoe> listShoes = dbContext.Shoes.ToList();
            List<Shoe> SaleShoes = listShoes.Where(item => item.IsSale == true).ToList();
            return View(SaleShoes);
        }
        public ActionResult SortShoes()
        {
            List<Shoe> listShoes = dbContext.Shoes.ToList();
            List<Shoe> ListShoesSort = listShoes.OrderBy(item => item.Price).ToList();
            return View(ListShoesSort);
        }
    }
}

SportsStore/Views/Shoes/CardShoes.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #Divcard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
    #Title {
        font-size: 50px;
        text-shadow: 2px 2px 2px rgb(80, 79, 76);
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1 id="Title">Shoes :</h1>
<button type="button" onclick="location.href = '@Url.Action("TableShoes","Shoes")'">Show table </button>
<button type="button" onclick="location.href = '@Url.Action("SaleShoes","Shoes")'">Show Sale Shoes </button>
<button type="button" onclick="location.href = '@Url.Action("SortShoes","Shoes")'">Show Sort Shoes </button>
<div id="Divcard">
    <br />
    @foreach (Shoe shoe in @Model)
    {
        <br />
        <section id="card">
            <h4>ShoeType : @shoe.ShoeType</h4>
            <h4>Company : @shoe.Company</h4>
            <h4>Price : @shoe.Price</h4>
            <img src="@shoe.Img" />
        </section>
    }
</div>

SportsStore/Views/Shoes/SaleShoes.cshtml
@using SportsStore.Models;



<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #Divcard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
    #Title {
        font-size: 50px;
        text-shadow: 2px 2px 2px rgb(80, 79, 76);
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1 id="Title">Sale Shoes :</h1>
<button type="button" onclick="location.href = '@Url.Action("TableShoes","Shoes")'">Show table </button>
<button type="button" onclick="location.href = '@Url.Action("SortShoes","Shoes")'">Show Sort Shoes </button>
<button type="button" onclick="location.href = '@Url.Action("CardShoes","Shoes")'">Show All Shoes </button>
<div id="Divcard">
    <br />
    @foreach (Shoe shoe in @Model)
    {
        <br />
        <section id="card">
            <h4>ShoeType : @shoe.ShoeType</h4>
            <h4>Company : @shoe.Company</h4>
            <h4>Price : @shoe.Price</h4>
            <img src="@shoe.Img" />
        </section>
    }
</div>

SportsStore/Views/Shoes/ShowTable.cshtml
@using SportsStore.Models;
@{
    ViewBag.Title = "ShowTable";
}
<button type="button" onclick="location.href = '@Url.Action("AllTheShoes","Shoes")'">click to change </button>
<style>
    table, th, td {
        border: 2px solid black;
    }
</style>
<div id="Table">
    <table width="100%">
        <tr>
            <th>ShoeType</th>
            <th>Company</th>
            <th>Model</th>
            <th>Price</th>
            <th>Amount</th>
            <th>IsSale</th>
            <th>Img</th>
        </tr>
        <tr>
            @foreach (Shoe shoe in @ViewBag.Shoes)
            {
                <td>@shoe.ShoeType</td>
                <td>@shoe.Company</td>
                <td>@shoe.Model</td>
                <td>@shoe.Price</td>
                <td>@shoe.Amount</td>
                <td>@shoe.IsSale</td>
                <td><img src="@shoe.Img" width="40px" height="40px" /></td>
            <tr />
        }
            <table />

    </div>

SportsStore/Views/Shoes/SortShoes.cshtml
@using SportsStore.Models;



<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #Divcard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
    #Title {
        font-size: 50px;
        text-shadow: 2px 2px 2px rgb(80, 79, 76);
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1 id="Title">Sort Shoes :</h1>
<button type="button" onclick="location.href = '@Url.Action("TableShoes","Shoes")'">Show table </button>
<button type="button" onclick="location.href = '@Url.Action("CardShoes","Shoes")'">Show All Shoes </button>
<button type="button" onclick="location.href = '@Url.Action("SaleShoes","Shoes")'">Show Sale Shoes </button>
<div id="Divcard">
    <br />
    @foreach (Shoe shoe in @Model)
    {
        <br />
        <section id="card">
            <h4>ShoeType : @shoe.ShoeType</h4>
            <h4>Company : @shoe.Company</h4>
            <h4>Price : @shoe.Price</h4>
            <img src="@shoe.Img" />
        </section>
    }
</div>

SportsStore/Views/Shoes/TableShoes.cshtml
@using SportsStore.Models;
@{
    ViewBag.Title = "ShowTable";
}

<style>
    #TableShoes {
        width: 90%;
        border-collapse: collapse;
        margin-left: 10%;
        margin-bottom: 1%;
        padding: 10%;
        margin:3%;
    }
    #TableShoes,
    th,
    td {
        text-align: center;
        border: 1px solid black;
        background-color: rgb(249, 228, 200);
    }

    #TableShoes,
    th {
        height: 50px;
    }

        #TableShoes tr {
            border: 3px solid black;
        }
    #Title {
        font-size: 50px;
        text-shadow: 2px 2px 2px rgb(80, 79, 76);
    }

    button {
        @*border: none;
        *@ background: rgb(249, 207, 147);
        font-weight: bold;
        font-size: large;
    }
</style>
<div>
    <br />
    <h1 id="Title">Table Shoes : </h1>
    <button type="button" onclick="location.href = '@Url.Action("CardShoes","Shoes")'">click to all the Shoes </button>
    <button type="button" onclick="location.href = '@Url.Action("SortShoes","Shoes")'">Show Sort Shoes </button>
    <button type="button" onclick="location.href = '@Url.Action("SaleShoes","Shoes")'">Show Sale Shoes </button>
    <table id="TableShoes">
        <tr>
            <th>ShoeType</th>
            <th>Company</th>
            <th>Model</th>
            <th>Price</th>
            <th>Amount</th>
            <th>IsSale</th>
            <th>Img</th>
        </tr>
        <tr>
            @foreach (Shoe shoe in @Model)
            {
                <td>@shoe.ShoeType</td>
                <td>@shoe.Company</td>
                <td>@shoe.Model</td>
                <td>@shoe.Price</td>
                <td>@shoe.Amount</td>
                <td>@shoe.IsSale</td>
                <td><img src="@shoe.Img" width="40px" height="40px" /></td>
            <tr />
        }
            <table />

    </div>
    <br />