SportsStore/Controllers/API/ShirtController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SportsStore.Controllers.API
{
    public class ShirtController : ApiController
    {
        
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();
        string TypeOfTheCloth = "shirt";

        // GET: api/Shirt
        public IHttpActionResult Get()
        {
            try { 
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            return Ok(new { ListShirt });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: api/Shirt/5
        public IHttpActionResult Get(int id)
        {
            try { 
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            Clothing shirt = ListShirt.Find(item => item.Id == id);
            return Ok(new { shirt });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // POST: api/Shirt
        public IHttpActionResult Post([FromBody] Clothing shirt)
        {
            try { 
            dbContext.Clothings.InsertOnSubmit(shirt);
            dbContext.SubmitChanges();
            return Ok("you add one more");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // PUT: api/Shirt/5
        public IHttpActionResult Put(int id, [FromBody] Clothing shirt)
        {
            try { 
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            Clothing shirtToChange = ListShirt.Find(item => item.Id == id);
            shirtToChange.ClothModel = shirt.ClothModel;
            shirtToChange.IsShort = shirt.IsShort;
            shirtToChange.Amount = shirt.Amount;
            shirtToChange.IsDreyfit = shirt.IsDreyfit;
            shirtToChange.Gender = shirt.Gender;
            shirtToChange.Price = shirt.Price;
            shirtToChange.Img = shirtToChange.Img;
            shirtToChange.Company = shirtToChange.Company;
            dbContext.SubmitChanges();
            //shirtToChange.ClothType = shirtToChange.ClothType;
            return Ok("you upDate");
        }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
    }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
}
        }

        // DELETE: api/Shirt/5
        public IHttpActionResult Delete(int id)
        {
            try { 
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            Clothing shirtToDelete = ListShirt.Find(item => item.Id == id);
            dbContext.Clothings.DeleteOnSubmit(shirtToDelete);
            dbContext.SubmitChanges();
            return Ok("you delete");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

SportsStore/Controllers/ShirtController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ShirtController : Controller
    {
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();
        string TypeOfTheCloth = "shirt";
        // GET: Shirt

        public ActionResult ShirtTable()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            return View(ListShirt);
        }
        public ActionResult ShirtCard()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            
            return View(ListShirt);
        }
        public ActionResult LongShirt()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListLongShirt = ListShirt.Where(item => item.IsShort ==false ).ToList();
            return View(ListLongShirt);
        }
        
        public ActionResult TShirt()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListTShirt = ListShirt.Where(item => item.IsShort == true).ToList();
            return View(ListTShirt);
        }
        public ActionResult DreyfitShirt()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListDreyfitShirt = ListShirt.Where(item => item.IsDreyfit == true).ToList();
            return View(ListDreyfitShirt);
        }
        public ActionResult SortShirt()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListShirtSort =ListShirt.OrderBy(item => item.Price).ToList();
            return View(ListShirtSort);
        }
        public ActionResult FemaleShirt()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListFemaleShirt = ListShirt.Where(item => item.Gender == "female").ToList();
            return View(ListFemaleShirt);
        }
        public ActionResult MaleShirt()
        {
            List<Clothing> ListShirt = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListMaleShirt = ListShirt.Where(item => item.Gender == "male").ToList();
            return View(ListMaleShirt);
        }
       

    }
}

SportsStore/Views/Shirt/DreyfitShirt.cshtml
@using SportsStore.Models;
<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

        button {
            background-color: rgb(238, 195, 115);
            font-weight: bold;
            @*border: none;*@
            font-size: large;
            transition: 2s;
        }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Dreyfits Shirt</h1>
<button type="button" onclick="location.href = '@Url.Action("ShirtCard","Shirt")'">Shirt Card </button>
<button type="button" onclick="location.href = '@Url.Action("ShirtTable","Shirt")'">Shirt Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongShirt","Shirt")'">Long Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("TShirt","Shirt")'">Short TShirt </button>
<button type="button" onclick="location.href = '@Url.Action("SortShirt","Shirt")'">Sort Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("MaleShirt","Shirt")'">Male Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("FemaleShirt","Shirt")'">Female Shirts </button>
<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />
        </section>
    }
</div>

SportsStore/Views/Shirt/FemaleShirt.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 60vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

        button {
            background-color: rgb(238, 195, 115);
            font-weight: bold;
            @*border: none;*@
            font-size: large;
            transition: 2s;
        }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>shirt for the Ladies</h1>
<button type="button" onclick="location.href = '@Url.Action("ShirtCard","Shirt")'">Card Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("ShirtTable","Shirt")'">Shirt Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongShirt","Shirt")'">Long Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("TShirt","Shirt")'">Short TShirt </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitShirt","Shirt")'">Dreyfit Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("SortShirt","Shirt")'">Sort Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("MaleShirt","Shirt")'">Male Shirts </button>

<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />
        </section>
    }
</div>

SportsStore/Views/Shirt/LongShirt.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

        button {
            background-color: rgb(238, 195, 115);
            font-weight: bold;
            @*border: none;*@
            font-size: large;
            transition: 2s;
        }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Long Shirt </h1>
<button type="button" onclick="location.href = '@Url.Action("ShirtCard","Shirt")'">Card Shirt</button>
<button type="button" onclick="location.href = '@Url.Action("ShirtTable","Shirt")'">Shirt Table </button>
<button type="button" onclick="location.href = '@Url.Action("TShirt","Shirt")'">Short TShirt </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitShirt","Shirt")'">Dreyfit Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("SortShirt","Shirt")'">Sort Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("MaleShirt","Shirt")'">Male Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("FemaleShirt","Shirt")'">Female Shirts </button>
<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />
        </section>
    }
</div>

SportsStore/Views/Shirt/MaleShirt.cshtml
@using SportsStore.Models;
<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

        button {
            background-color: rgb(238, 195, 115);
            font-weight: bold;
            @*border: none;*@
            font-size: large;
            transition: 2s;
        }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>

<br />
<h1>Shirt for the Mens </h1>
<button type="button" onclick="location.href = '@Url.Action("ShirtCard","Shirt")'">Shirt card </button>
<button type="button" onclick="location.href = '@Url.Action("ShirtTable","Shirt")'">Shirt Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongShirt","Shirt")'">Long Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("TShirt","Shirt")'">Short TShirt </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitShirt","Shirt")'">Dreyfit Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("SortShirt","Shirt")'">Sort Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("FemaleShirt","Shirt")'">Female Shirts </button>

<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />
        </section>
    }
</div>

SportsStore/Views/Shirt/ShirtCard.cshtml
@using SportsStore.Models;
<style>
    body {
        background-color: rgb(238, 195, 115);

    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
    #Title {
        font-size: 50px;
        text-shadow: 2px 2px 2px rgb(80, 79, 76);
    }
</style>
<br />
<h2 id="Title">Shirt  </h2>
<button type="button" onclick="location.href = '@Url.Action("ShirtTable","Shirt")'">Shirt Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongShirt","Shirt")'">Long Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("TShirt","Shirt")'">Short TShirt </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitShirt","Shirt")'">Dreyfit Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("SortShirt","Shirt")'">Sort Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("MaleShirt","Shirt")'">Male Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("FemaleShirt","Shirt")'">Female Shirts </button>

@*<select id="shirts">
        <option class="option" value="card">card</coption>
        <option value="longShirt">longShirt</option>
        <option value="DreyfitShirts">DreyfitShirts</option>
        <option value="sort">sort</option>
        <option value="table">table</option>
    </select>*@


@*@switch ()
    {
        case "card" :
            <h1>card</h1>
            break;
        case "longShirt":
            <h1>longg</h1>
        case "DreyfitShirts":
    <h1>DreyfitShirts</h1>
            break;
        default:
    <h1>aaaa</h1>
            break;

    }*@

<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />
        </section>
    }
</div>

SportsStore/Views/Shirt/ShirtTable.cshtml
@using SportsStore.Models;

<style>
    #TableShirt {
        width: 90%;
        border-collapse: collapse;
        margin-left: 10%;
        margin-bottom: 1%;
        padding: 10%;
        margin: 3%;
    }

    #TableShirt,
    th,
    td {
        text-align: center;
        border: 1px solid black;
        background-color: rgb(249, 228, 200);
    }

    #TableShirt,
    th {
        height: 50px;
    }

        #TableShirt tr {
            border: 3px solid black;
        }

    button {
        @*border: none;
        *@ background: rgb(249, 207, 147);
        font-weight: bold;
        font-size: large;
    }
</style>
<br />
<h1>Shirts </h1>
<button type="button" onclick="location.href = '@Url.Action("ShirtCard","Shirt")'">Card shirt </button>
<button type="button" onclick="location.href = '@Url.Action("LongShirt","Shirt")'">Long Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("TShirt","Shirt")'">Short TShirt </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitShirt","Shirt")'">Dreyfit Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("SortShirt","Shirt")'">Sort Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("MaleShirt","Shirt")'">Male Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("FemaleShirt","Shirt")'">Female Shirts </button>
<div>
    <table id="TableShirt">
        <tr>
            <th>ClothModel</th>
            <th>Company</th>
            <th>IsShort</th>
            <th>Price</th>
            <th>Amount</th>
            <th>IsDreyfit</th>
            <th>Gender</th>
            <th>Img</th>
        </tr>
        <tr>
            @foreach (Clothing shirt in @Model)
            {
                <td>@shirt.ClothModel</td>
                <td> @shirt.Company</td>
                <td>@shirt.IsShort</td>
                <td>@shirt.Price</td>
                <td> @shirt.Amount</td>
                <td> @shirt.IsDreyfit</td>
                <td> @shirt.Gender</td>
                <td><img src="@shirt.Img" width="100px" height="40px" /></td>
            <tr />
        }
            <table />

    </div>

SportsStore/Views/Shirt/SortShirt.cshtml
@using SportsStore.Models;
<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h2>Shirt Sort</h2>
<button type="button" onclick="location.href = '@Url.Action("ShirtCard","Shirt")'">Shirt card </button>
<button type="button" onclick="location.href = '@Url.Action("ShirtTable","Shirt")'">Shirt Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongShirt","Shirt")'">Long Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("TShirt","Shirt")'">Short TShirt </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitShirt","Shirt")'">Dreyfit Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("MaleShirt","Shirt")'">Male Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("FemaleShirt","Shirt")'">Female Shirts </button>


<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />
        </section>
    }
</div>

SportsStore/Views/Shirt/TShirt.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Short T-Shirt</h1>
<button type="button" onclick="location.href = '@Url.Action("ShirtCard","Shirt")'">Shirt Card </button>
<button type="button" onclick="location.href = '@Url.Action("ShirtTable","Shirt")'">Shirt Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongShirt","Shirt")'">Long Shirt </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitShirt","Shirt")'">Dreyfit Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("SortShirt","Shirt")'">Sort Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("MaleShirt","Shirt")'">Male Shirts </button>
<button type="button" onclick="location.href = '@Url.Action("FemaleShirt","Shirt")'">Female Shirts </button>
<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {

        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />

        </section>

    }

</div>