SportsStore/Controllers/API/SportsEquipmentController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SportsStore.Controllers.API
{
    public class SportsEquipmentController : ApiController
    {
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();
        // GET: api/SportsEquipment
        public IHttpActionResult Get()
        {
            try
            {
                List<SportsEquipment> ListsportsEquipment = dbContext.SportsEquipments.ToList();
                return Ok(new { ListsportsEquipment });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: api/SportsEquipment/5
        public IHttpActionResult Get(int id)
        {
            try
            {
                SportsEquipment sportsEquipment = dbContext.SportsEquipments.First(item => item.Id == id);
                return Ok(new { sportsEquipment });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

        }

        // POST: api/SportsEquipment
        public IHttpActionResult Post([FromBody] SportsEquipment Equipment)
        {
            try { 
            dbContext.SportsEquipments.InsertOnSubmit(Equipment);
            dbContext.SubmitChanges();
            List<SportsEquipment> ListsportsEquipment = dbContext.SportsEquipments.ToList();
            return Ok(new { ListsportsEquipment });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // PUT: api/SportsEquipment/5
        public IHttpActionResult Put(int id, [FromBody]SportsEquipment Equipment)
        {
            try { 
            SportsEquipment sportsEquipmentToUpdate = dbContext.SportsEquipments.First(item => item.Id == id);
            sportsEquipmentToUpdate.IdOfTheGroup = Equipment.IdOfTheGroup;
            sportsEquipmentToUpdate.Amount=Equipment.Amount;
            sportsEquipmentToUpdate.sportType=Equipment.sportType;
            sportsEquipmentToUpdate.Price=Equipment.Price;
            sportsEquipmentToUpdate.Img=Equipment.Img;
            sportsEquipmentToUpdate.Company=Equipment.Company;
            sportsEquipmentToUpdate.ProductName=Equipment.ProductName;
            dbContext.SubmitChanges();
            return Ok("you Update the ");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // DELETE: api/SportsEquipment/5
        public IHttpActionResult Delete(int id)
        {
            try { 
            SportsEquipment sportsEquipmentToDelete = dbContext.SportsEquipments.First(item => item.Id == id);
            dbContext.SportsEquipments.DeleteOnSubmit(sportsEquipmentToDelete);
            dbContext.SubmitChanges();
            return Ok("you delete the Equipment");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

SportsStore/Controllers/SportsEquipmentController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class SportsEquipmentController : Controller
    {
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();
        string g = "football";
        // GET: SportsEquipment

        public ActionResult SportsEquipmentCard()
        {
            List<SportsEquipment> listSportsEquipment = dbContext.SportsEquipments.ToList();
            return View(listSportsEquipment);
        }
        public ActionResult SportsEquipmentTable()
        {
            List<SportsEquipment> listSportsEquipment = dbContext.SportsEquipments.ToList();
            return View(listSportsEquipment);
        }
        public ActionResult EquipmentFootball()
        {
            List<SportsEquipment> listSportsEquipment = dbContext.SportsEquipments.ToList();
            List<SportsEquipment> listEquipmentFootball = listSportsEquipment.Where(item => item.sportType == "football").ToList();
            return View(listEquipmentFootball);
        }
        public ActionResult EquipmentBasketball()
        {
            List<SportsEquipment> listSportsEquipment = dbContext.SportsEquipments.ToList();
            List<SportsEquipment> EquipmentBasketball = listSportsEquipment.Where(item => item.sportType == "basketball").ToList();
            return View(EquipmentBasketball);
        }
        public ActionResult EquipmentSort()
        {
            List<SportsEquipment> listSportsEquipment = dbContext.SportsEquipments.ToList();
            List<SportsEquipment> ListSportsEquipmentSort = listSportsEquipment.OrderBy(item => item.Price).ToList();
            return View(ListSportsEquipmentSort);
        }
    }
}

SportsStore/Views/SportsEquipment/EquipmentBasketball.cshtml
@using SportsStore.Models;


<h2>AllTheShoes</h2>
<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #Divcard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Equipment for Basketball</h1>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentCard","SportsEquipment")'">Show Card </button>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentTable","SportsEquipment")'">Show table </button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentFootball","SportsEquipment")'">click To SportsEquipment Football</button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentSort","SportsEquipment")'">click To Sort SportsEquipments </button>
<div id="Divcard">
    @foreach (SportsEquipment SportsEquipment in @Model)
    {
        <section id="card">
            <br />
            <h4>ShoeType : @SportsEquipment.sportType</h4>
            <h4>Company : @SportsEquipment.Company</h4>
            <h4>Price : @SportsEquipment.Price</h4>
            <br />
            <img src="@SportsEquipment.Img" />
        </section>
    }

</div>

SportsStore/Views/SportsEquipment/EquipmentFootball.cshtml
@using SportsStore.Models;


<h2>AllTheShoes</h2>
<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #Divcard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Equipment for Foottball</h1>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentCard","SportsEquipment")'">Show Card </button>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentTable","SportsEquipment")'">Show table </button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentBasketball","SportsEquipment")'">click To SportsEquipment Basketball</button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentSort","SportsEquipment")'">click To Sort SportsEquipments </button>
<div id="Divcard">
    @foreach (SportsEquipment SportsEquipment in @Model)
    {
        <section id="card">
            <br />
            <h4>ShoeType : @SportsEquipment.sportType</h4>
            <h4>Company : @SportsEquipment.Company</h4>
            <h4>Price : @SportsEquipment.Price</h4>
            <br />
            <img src="@SportsEquipment.Img" />
        </section>
    }

</div>

SportsStore/Views/SportsEquipment/EquipmentSort.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #Divcard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Equipment Sort</h1>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentCard","SportsEquipment")'">Show Card </button>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentTable","SportsEquipment")'">Show table </button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentBasketball","SportsEquipment")'">click To SportsEquipment Basketball</button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentFootball","SportsEquipment")'">click To SportsEquipment Football</button>
<div id="Divcard">
    @foreach (SportsEquipment SportsEquipment in @Model)
    {
        <section id="card">
            <br />
            <h4>ShoeType : @SportsEquipment.sportType</h4>
            <h4>Company : @SportsEquipment.Company</h4>
            <h4>Price : @SportsEquipment.Price</h4>
            <br />
            <img src="@SportsEquipment.Img" />
        </section>
    }

</div>

SportsStore/Views/SportsEquipment/SportsEquipmentCard.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #Divcard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<h1>Equipment for Sport</h1>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentTable","SportsEquipment")'">Show table </button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentBasketball","SportsEquipment")'">click To SportsEquipment Basketball</button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentFootball","SportsEquipment")'">click To SportsEquipment Football</button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentSort","SportsEquipment")'">click To Sort SportsEquipments </button>
<div id="Divcard">
    @foreach (SportsEquipment SportsEquipment in @Model)
    {
        <section id="card">
            <br />
            <h4>ShoeType : @SportsEquipment.sportType</h4>
            <h4>Company : @SportsEquipment.Company</h4>
            <h4>Price : @SportsEquipment.Price</h4>
            <br />
            <img src="@SportsEquipment.Img" />
        </section>
    }

</div>

SportsStore/Views/SportsEquipment/SportsEquipmentTable.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #TableShoes {
        width: 90%;
        border-collapse: collapse;
        margin-left: 10%;
        margin-bottom: 1%;
        padding: 10%;
        margin: 3%;
    }

    #TableShoes,
    th,
    td {
        text-align: center;
        border: 1px solid black;
        background-color: rgb(249, 228, 200);
    }

    #TableShoes,
    th {
        height: 50px;
    }

        #TableShoes tr {
            border: 3px solid black;
        }

    button {
        @*border: none;
        *@ background: rgb(249, 207, 147);
        font-weight: bold;
        font-size: large;
    }
</style>
<br />
<h1>Table Equipment : </h1>
<button type="button" onclick="location.href = '@Url.Action("SportsEquipmentCard","SportsEquipment")'">Show Equipment   </button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentBasketball","SportsEquipment")'">click To SportsEquipment Basketball  </button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentFootball","SportsEquipment")'">click To SportsEquipment Football  </button>
<button type="button" onclick="location.href = '@Url.Action("EquipmentSort","SportsEquipment")'">click To Sort SportsEquipments </button>
<div>
    <table id="TableShoes">
        <tr>
            <th>Name</th>
            <th>sportType</th>
            <th>Company</th>
            <th>Price</th>
            <th>Amount</th>
            <th>Model</th>
            <th>Img</th>
        </tr>
        <tr>

            @foreach (SportsEquipment SportsEquipment in @Model)
            {
                <td>@SportsEquipment.ProductName</td>
                <td>@SportsEquipment.sportType</td>
                <td>@SportsEquipment.Company</td>
                <td>@SportsEquipment.Price</td>
                <td>@SportsEquipment.Amount</td>
                <td>@SportsEquipment.ModelProduct</td>
                <td><img src="@SportsEquipment.Img" width="40px" height="40px" /></td>
            <tr />
        }
            <table />

    </div>
    <br />
    </div>