SportsStore/Controllers/API/PantsController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SportsStore.Controllers.API
{
    public class PantsController : ApiController
    {
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();
        string TypeOfTheCloth = "pants";
        // GET: api/Pants
        public IHttpActionResult Get()
        {
            try { 
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            return Ok(new { ListPants });
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // GET: api/Pants/5
        public IHttpActionResult Get(int id)
        {
            try { 
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            Clothing pants = ListPants.Find(item => item.Id == id);
            return Ok(new { pants });
        }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
    }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
}
        }

        // POST: api/Pants
        public IHttpActionResult Post([FromBody] Clothing pants)
        {
            try { 
            dbContext.Clothings.InsertOnSubmit(pants);
            dbContext.SubmitChanges();
            return Ok("you add one more");
        }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
    }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
}
        }

        // PUT: api/Pants/5
        public IHttpActionResult Put(int id, [FromBody]Clothing pants)
        {
            try { 
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            Clothing pantsToChange = ListPants.Find(item => item.Id == id);
            pantsToChange.ClothModel = pants.ClothModel;
            pantsToChange.IsShort = pants.IsShort;
            pantsToChange.Amount = pants.Amount;
            pantsToChange.IsDreyfit = pants.IsDreyfit;
            pantsToChange.Gender = pants.Gender;
            pantsToChange.Price = pants.Price;
            pantsToChange.Img = pants.Img;
            pantsToChange.Company = pants.Company;
            dbContext.SubmitChanges();
            //pantsToChange.ClothType = pantsToChange.ClothType;
            return Ok("you upDate");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // DELETE: api/Pants/5
        public IHttpActionResult Delete(int id)
        {
            try { 
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            Clothing pantsToDelete = ListPants.Find(item => item.Id == id);
            dbContext.Clothings.DeleteOnSubmit(pantsToDelete);
            dbContext.SubmitChanges();
            return Ok("you delete");
            }
            catch (SqlException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

SportsStore/Controllers/PantsController.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class PantsController : Controller
    {
        StoreDbContextDataContext dbContext = new StoreDbContextDataContext();
        string TypeOfTheCloth = "pants";
        // GET: Pants
        
        public ActionResult TableOfPants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            return View(ListPants);
        }
        public ActionResult CardOfPants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            return View(ListPants);
        }
        public ActionResult LongPants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListLongPants = ListPants.Where(item => item.IsShort == false).ToList();
            return View(ListLongPants);
        }

        public ActionResult shortPants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListshortPants = ListPants.Where(item => item.IsShort == true).ToList();
            return View(ListshortPants);
        }
        public ActionResult DreyfitPants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListDreyfitPants = ListPants.Where(item => item.IsDreyfit == true).ToList();
            return View(ListDreyfitPants);
        }
        public ActionResult SortPants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListPantsSort = ListPants.OrderBy(item => item.Price).ToList();
            ViewBag.SortPants = ListPantsSort;
            return View(ListPantsSort);
        }
        public ActionResult FemalePants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListFemalePants = ListPants.Where(item => item.Gender == "female").ToList();
            return View(ListFemalePants);
        }
        public ActionResult MalePants()
        {
            List<Clothing> ListPants = dbContext.Clothings.Where(item => item.ClothType == TypeOfTheCloth).ToList();
            List<Clothing> ListMalePants = ListPants.Where(item => item.Gender == "male").ToList();
            return View(ListMalePants);
        }
    }
}

SportsStore/Views/Pants/CardOfPants.cshtml
@using SportsStore.Models;
<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
    #Title {
        font-size: 50px;
        text-shadow: 2px 2px 2px rgb(80, 79, 76);
    }
</style>

<br />
<h2 id="Title">Pants </h2>

<button type="button" onclick="location.href = '@Url.Action("TableOfPants","Pants")'"> To Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongPants","Pants")'"> To LongPants </button>
<button type="button" onclick="location.href = '@Url.Action("SortPants","Pants")'"> To SortPants </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitPants","Pants")'"> To DreyfitPants </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("FemalePants","Pants")'"> To FemalePants </button>
<button type="button" onclick="location.href = '@Url.Action("MalePants","Pants")'"> To MalePants </button>

<div id="DivCard">
    @foreach (Clothing shirt in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @shirt.ClothType</h4>
            <h4>Company : @shirt.Company</h4>
            <h4>Price : @shirt.Price</h4>
            <br />
            <img src="@shirt.Img" />
        </section>
    }
</div>

SportsStore/Views/Pants/DreyfitPants.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Dreyfit Pants</h1>
<button type="button" onclick="location.href = '@Url.Action("CardOfPants","Pants")'">To Pants </button>
<button type="button" onclick="location.href = '@Url.Action("TableOfPants","Pants")'"> To Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongPants","Pants")'"> To LongPants </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("SortPants","Pants")'"> To SortPants </button>
<button type="button" onclick="location.href = '@Url.Action("FemalePants","Pants")'"> To FemalePants </button>
<button type="button" onclick="location.href = '@Url.Action("MalePants","Pants")'"> To MalePants </button>

<div id="DivCard">
    @foreach (Clothing pants in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @pants.ClothType</h4>
            <h4>Company : @pants.Company</h4>
            <h4>Price : @pants.Price</h4>
            <br />
            <img src="@pants.Img" />
        </section>
    }
</div>

SportsStore/Views/Pants/FemalePants.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 60vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Pants for the Ladies</h1>
<button type="button" onclick="location.href = '@Url.Action("CardOfPants","Pants")'">To Pants </button>
<button type="button" onclick="location.href = '@Url.Action("TableOfPants","Pants")'"> To Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongPants","Pants")'"> To LongPants </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitPants","Pants")'"> To DreyfitPants </button>
<button type="button" onclick="location.href = '@Url.Action("SortPants","Pants")'"> To SortPants </button>
<button type="button" onclick="location.href = '@Url.Action("MalePants","Pants")'"> To MalePants </button>
<div id="DivCard">
    @foreach (Clothing Pants in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @Pants.ClothType</h4>
            <h4>Company : @Pants.Company</h4>
            <h4>Price : @Pants.Price</h4>
            <br />
            <img src="@Pants.Img" />
        </section>
    }
</div>

SportsStore/Views/Pants/LongPants.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Long Pants</h1>
<button type="button" onclick="location.href = '@Url.Action("CardOfPants","Pants")'">To Pants </button>
<button type="button" onclick="location.href = '@Url.Action("TableOfPants","Pants")'"> To Table </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitPants","Pants")'"> To DreyfitPants </button>
<button type="button" onclick="location.href = '@Url.Action("SortPants","Pants")'"> To SortPants </button>
<button type="button" onclick="location.href = '@Url.Action("FemalePants","Pants")'"> To FemalePants </button>
<button type="button" onclick="location.href = '@Url.Action("MalePants","Pants")'"> To MalePants </button>

<div id="DivCard">
    @foreach (Clothing pants in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @pants.ClothType</h4>
            <h4>Company : @pants.Company</h4>
            <h4>Price : @pants.Price</h4>
            <br />
            <img src="@pants.Img" />
        </section>
    }
</div>

SportsStore/Views/Pants/MalePants.cshtml
@using SportsStore.Models;
<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Pants for the Mens </h1>
<button type="button" onclick="location.href = '@Url.Action("CardOfPants","Pants")'">To card </button>
<button type="button" onclick="location.href = '@Url.Action("TableOfPants","Pants")'"> To Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongPants","Pants")'"> To LongPants </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitPants","Pants")'"> To DreyfitPants </button>
<button type="button" onclick="location.href = '@Url.Action("SortPants","Pants")'"> To SortPants </button>
<button type="button" onclick="location.href = '@Url.Action("FemalePants","Pants")'"> To FemalePants </button>

<div id="DivCard">
    @foreach (Clothing pants in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @pants.ClothType</h4>
            <h4>Company : @pants.Company</h4>
            <h4>Price : @pants.Price</h4>
            <br />
            <img src="@pants.Img" />
        </section>
    }
</div>

SportsStore/Views/Pants/SortPants.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Sort Pants</h1>
<button type="button" onclick="location.href = '@Url.Action("CardOfPants","Pants")'">To Pants </button>
<button type="button" onclick="location.href = '@Url.Action("TableOfPants","Pants")'"> To Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongPants","Pants")'"> To LongPants </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitPants","Pants")'"> To DreyfitPants </button>
<button type="button" onclick="location.href = '@Url.Action("FemalePants","Pants")'"> To FemalePants </button>
<button type="button" onclick="location.href = '@Url.Action("MalePants","Pants")'"> To MalePants </button>

<div id="DivCard">
    @foreach (Clothing pants in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @pants.ClothType</h4>
            <h4>Company : @pants.Company</h4>
            <h4>Price : @pants.Price</h4>
            <br />
            <img src="@pants.Img" />
        </section>
    }
</div>

SportsStore/Views/Pants/TableOfPants.cshtml
@using SportsStore.Models;

<style>
    #TablePants {
        width: 90%;
        border-collapse: collapse;
        margin-left: 10%;
        margin-bottom: 1%;
        padding: 10%;
        margin: 3%;
    }

    #TablePants,
    th,
    td {
        text-align: center;
        border: 1px solid black;
        background-color: rgb(249, 228, 200);
    }

    #TablePants,
    th {
        height: 50px;
    }

        #TablePants tr {
            border: 3px solid black;
        }

    button {
        @*border: none;
        *@ background: rgb(249, 207, 147);
        font-weight: bold;
        font-size: large;
    }
</style>
<br />
<h2> Table of Pants</h2>
<button type="button" onclick="location.href = '@Url.Action("CardOfPants","Pants")'">To pants </button>
<button type="button" onclick="location.href = '@Url.Action("LongPants","Pants")'"> To LongPants </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitPants","Pants")'"> To DreyfitPants </button>
<button type="button" onclick="location.href = '@Url.Action("shortPants","Pants")'"> To shortPants </button>
<button type="button" onclick="location.href = '@Url.Action("FemalePants","Pants")'"> To FemalePants </button>
<button type="button" onclick="location.href = '@Url.Action("MalePants","Pants")'"> To MalePants </button>
<div>
    <table id="TablePants">
        <tr>
            <th>ClothModel</th>
            <th>Company</th>
            <th>IsShort</th>
            <th>Price</th>
            <th>Amount</th>
            <th>IsDreyfit</th>
            <th>Gender</th>
            <th>Img</th>
        </tr>
        <tr>
            @foreach (Clothing pants in @Model)
            {
                <td>@pants.ClothModel</td>
                <td> @pants.Company</td>
                <td>@pants.IsShort</td>
                <td>@pants.Price</td>
                <td> @pants.Amount</td>
                <td> @pants.IsDreyfit</td>
                <td> @pants.Gender</td>
                <td><img src="@pants.Img" width="100px" height="40px" /></td>
            <tr />
        }
            <table />

    </div>

SportsStore/Views/Pants/shortPants.cshtml
@using SportsStore.Models;

<style>
    body {
        background-color: rgb(238, 195, 115);
    }

    #DivCard {
        width: 100%;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    #Card {
        font-size: large;
        width: 40vh;
        height: 50vh;
        box-shadow: 5px 5px 5px rgb(202, 150, 92);
        background: linear-gradient(rgb(244, 223, 186),rgb(238, 195, 115),rgb(202, 150, 92));
        margin: 2%;
        /* border: 6px solid rgb(226, 22, 15); */
        text-align: center;
        border-radius: 10%;
        transition: 2s;
    }
        @*#card:hover {
            width: 5%;
            height: 5%;
        }*@
        #Card img {
            width: 60%;
            height: 40%;
            border-radius: 10%;
        }

    button {
        background-color: rgb(238, 195, 115);
        font-weight: bold;
        @*border: none;
        *@ font-size: large;
        transition: 2s;
    }
            @*button:hover {
                width: 5%;
                height: 5%;
            }*@
</style>
<br />
<h1>Short Pants</h1>
<button type="button" onclick="location.href = '@Url.Action("CardOfPants","Pants")'">To Pants </button>
<button type="button" onclick="location.href = '@Url.Action("TableOfPants","Pants")'"> To Table </button>
<button type="button" onclick="location.href = '@Url.Action("LongPants","Pants")'"> To LongPants </button>
<button type="button" onclick="location.href = '@Url.Action("DreyfitPants","Pants")'"> To DreyfitPants </button>
<button type="button" onclick="location.href = '@Url.Action("SortPants","Pants")'"> To SortPants </button>
<button type="button" onclick="location.href = '@Url.Action("FemalePants","Pants")'"> To FemalePants </button>
<button type="button" onclick="location.href = '@Url.Action("MalePants","Pants")'"> To MalePants </button>

<div id="DivCard">
    @foreach (Clothing pants in @Model)
    {
        <section id="Card">
            <br />
            <h4>Type : @pants.ClothType</h4>
            <h4>Company : @pants.Company</h4>
            <h4>Price : @pants.Price</h4>
            <br />
            <img src="@pants.Img" />
        </section>
    }
</div>